#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t mrsicmsnotes \
		         -r none \
                         -C "start_jupyter -t -T @tool landing.ipynb" \
                         -u anaconda-7
