#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t mrsicmsnotes \
                         -C "start_jupyter -t -T @tool visualizations.ipynb" \
                         -u anaconda-7 #should just start with mrsicms kernel
